/** Apache-2.0. Package the production shader exports; never maintain a second implementation. */
import {readFile, writeFile} from 'node:fs/promises';

const names=['material','content','endpoint'];
const sources=Object.fromEntries(await Promise.all(names.map(async name=>
  [name,(await readFile(new URL(`shaders/${name}.sksl`,import.meta.url),'utf8')).replace(/\r\n/g,'\n')])));
const output='// Apache-2.0. Generated by generate-shaders.mjs from the production SkSL exports.\n'+
  '// Do not edit; npm test checks identity. No filesystem, fetch or loader needed by consumers.\n'+
  `export const glassShaderSources = Object.freeze(${JSON.stringify(sources,null,2)});\n`;
const target=new URL('shaders.mjs',import.meta.url);
if(process.argv.includes('--check')) {
  const actual=await readFile(target,'utf8').catch(error=>{if(error.code==='ENOENT')return '';throw error;});
  if(actual.replace(/\r\n/g,'\n')!==output)
    throw new Error('Bundled shaders are stale. Run npm run generate:shaders in ports/skia.');
  console.log('Bundled shader sources match all three production exports.');
} else {
  await writeFile(target,output);
  console.log('Generated shaders.mjs from the three production exports.');
}
